# Deployment da aplicação
apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversao-temperatura
spec:
  replicas: 2
  selector:
    matchLabels:
      app: conversao-temperatura
  template:
    metadata:
      labels:
        app: conversao-temperatura
    spec:
      containers:
      - name: conversao-temperatura
        image: psloureiro/conversao-temperatura:latest
---
# Deployment do serviço associado à aplicação
apiVersion: v1
kind: Service
metadata:
  name: conversao-temperatura
spec:
  selector:
    app: conversao-temperatura
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30000
  type: NodePort
  